name: 'Publish Chrome Extension'
description: 'Update and Publish Chrome Extension to Chrome Webstore'
inputs:
  path-to-extension-folder:
    description: 'The folder where the chrome extension is located'
    default: 'dist'
    required: true
  extension-id:
    description: 'The id of the extension. Can be seen in the webstore url'
    required: true
  client-id:
    description: 'The Google OAuth2 client id allowed to operate the Chrome webstore api'
    required: true
  client-secret:
    description: 'Google OAuth2 client secret'
    required: true
  refresh-token:
    description: 'Google OAuth2 refresh token'
    required: true
  publishTarget:
    description: 'Who is allowed to get the extension'
    required: false
    default: 'default'
  only-upload:
    description: 'Should only upload to Chrome webstore and not publish'
    default: false
  latestReleaseVersion:
    description: 'Latest github release version (needs to get bumped)'
    required: true
  github-token:  # id of input
    description: 'The repository token, i.e. secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'node16'
  main: 'index.js'